'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BeneficiaryDetailsControl
    
    '''<summary>
    '''chkAddDependant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAddDependant As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''cmdAddDependant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddDependant As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtMemberNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMemberNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSuffix As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFirstName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSurname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSurname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboMaritalStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMaritalStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboHealthStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboHealthStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboDisabilityStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDisabilityStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboLevelOfEducation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboLevelOfEducation As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboRegularity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRegularity As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboOpharnhood control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboOpharnhood As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboMajorSourceIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMajorSourceIncome As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboCondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCondition As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboAttendance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAttendance As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cboDisability control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDisability As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''radDateofBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radDateofBirth As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''cboSex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboSex As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtNationlIDNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNationlIDNo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cboRelationships control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRelationships As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''pnlError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmdSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''cmdClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtBeneficiaryID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBeneficiaryID1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtParentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParentID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''radBenListing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radBenListing As Global.Telerik.Web.UI.RadGrid
End Class
